### ISSUE TITLE
Screenshots for F-Droid 

### ISSUE THREAD

**Issue by mondlicht-und-sterne** [techie66/EngineDataLogger---Dashboard#2]
You can add Screenshots for F-Droid, too, if you want. https://f-droid.org/en/docs/All_About_Descriptions_Graphics_and_Screenshots/ https://gitlab.com/snippets/1895688 That was simply information about what is still possible. You would then only have to enter the screenshots in fastlane.

**Comment by techie66** [comment]
I have been planning on this for a while. Now that its an actual issue I'll probably get it done sooner. Thanks!

**Comment by mondlicht-und-sterne** [comment]
thank you that would be great

**Comment by techie66** [comment]
1.3 released. Included and verified
