### ISSUE TITLE
Add app icon to F-droid

### ISSUE THREAD

**Issue by inson1** [techie66/EngineDataLogger---Dashboard#8]

**Comment by techie66** [comment]
Where did it go? It had an icon on F-Droid until the 1.6 release.

I can see the apk on fdroid has the icon properly embedded in it. If I build it myself it does too. I will try adding the icon explicitly to the Triple-T metadata and see if that fixes it.

**Comment by inson1** [comment]
yes or fastlane

https://f-droid.org/docs/All_About_Descriptions_Graphics_and_Screenshots

**Comment by techie66** [comment]
fixed
Icon appears in Fdroid again.
